z.lua

Using the "&&" operator returns the exit code of the first failed
command, and when `$_ZL_ECHO` is unbind always return 1.

Don't return failed exit code when $_ZL_ECHO is unbind

---

z.lua

Every time you changed dir, there will be a lua_XXXXXX file created in /tmp, and will not be removed. These files is created by `os.tmpname()`, there are two calls in z.lua:
1. `os.tmpname()` in `math.random_init` is used to create a random string for seed. We need to delete tmp file after use.
2. `os.tmpname()` in `data_save` also used to create a random string for tmp db file,  for example `tmpname: /Users/fannheyward/.zlua.RK2Nq7qjU1E6154899255913512`. In this case, the sub string is not needed, cause the `tmpname` already has random string by `math.random_string` and `os.time()` for timestamp, so just delete `os.tmpname()` calls.

fix: no more lua_XXXXXX temp files

---

z.lua

otherwise it shows warning like `warning: line editing not enabled`

Do not bind fzf completion on dumb terminals

---

z.lua

see https://github.com/skywind3000/z.lua/issues/49

fix spurious file not exists

---

z.lua.plugin.zsh

z.lua didn't work for me because it couldn't find lua because I had `which` aliased to `type -a`. `\which` will use the non-aliased version.

Use \which in case user has it aliased to type -a

---

z.lua

z.lua unnecessarily changes zsh hooks to be `unique`. This slightly changes the default behaviour of zsh hooks and is actually not needed because there's a check for the presence of `_zlua_precmd` on the following line.

Setting zsh-hooks to be unique is not necessary

---

z.lua

When sourcing `z.lua` a semicolon is added to the end of `PROMPT_COMMAND`. That makes adding additional commands to `PROMPT_COMMAND` more cumbersome because it requires checking for the last `;` character instead of only checking if the variable exists. Having two semicolons in `PROMPT_COMMAND` is an error. 
For example (from my bashrc):
```
if ! [[ "${PROMPT_COMMAND:-}" =~ __prompt_command ]]; then
PROMPT_COMMAND="__prompt_command${PROMPT_COMMAND:+;$PROMPT_COMMAND};__precmd"
fi
```
won't work because `z.lua` added a semicolon to `PROMPT_COMMAND` and bash will complain about syntax error near unexpected token `;;`

Do not append semicolon to PROMPT_COMMAND

---

z.lua.plugin.zsh

Increase flexibility: allow the user to customize _ZL_FZF_FLAG before the zsh plugin is loaded

[zsh plugin] allow the user to customize _ZL_FZF_FLAG beforehand

---

z.lua.plugin.zsh

aliases are broken if _ZL_CMD is set to anything other than z

Introduce _ZL_NO_ALIASES to skip creating aliases

---

z.lua

`compctl` is ancient and many users even [completly disable it](https://github.com/search?q=zstyle+%27%3Acompletion%3A*%27+use-compctl+false&type=Code).
This PR replace it with mordern [compsys](http://zsh.sourceforge.net/Doc/Release/Completion-System.html).
Related issue: [fzf-tab#44](https://github.com/Aloxaf/fzf-tab/issues/44)

Improve zsh's completion

---

z.lua.plugin.zsh

`which` is very slow.
Simple benchmark:
```
$ time ( for i in {1..100}; do zsh z.lua.plugin.zsh; done )
18.54s user 2.29s system 102% cpu 20.340 total
$ time ( for i in {1..100}; do zsh z.lua.plugin.zsh; done )
0.84s user 0.37s system 104% cpu 1.164 total
```
22 times faster!

Use `command -v` to reduce zsh startup time

---

ranger_zlua.py

`z -I` had 2 issues:
- it used  `subprocess.check_output()`, but didn't UTF-8 decode the string (like the `if mode` statement's `else` branch does on row 80)
- it wasn't actually interactive, like `-I` is supposed to be (subprocess.check_output()` is not interactive)
I'm not sure why `-I` mode was originally treated differently from e.g. `-i` mode, but the same code works for both.
I took the `redraw_window` console command from the original `-I` mode code, because without it the screen updates a bit slower, causing an ugly "flash".

Fix `z -I` in ranger_zlua.py

---

README.md
z.lua

if other prompt_filter priority greater than z.lua's priority , and return true, z.lua will not register prompt success.

add _ZL_CLINK_PROMPT_PRIORITY set clink prompt register priority.

---

z.lua

This makes `z -` have the available flags show up as completions.
Note:  requires either Clink <= v0.4.9 or Clink >= v1.1.**13**, which is not yet published.  Making this change in z.lua helped me find a bug in Clink v1.1.12 where backward compatibility for `clink.arg.register_parser` wasn't working properly.  The fixed Clink v1.1.13 will be published later today or tomorrow.  The change here can be tested and verified in Clink v0.4.x, though.
UPDATE:  Clink v1.1.13 has been published and the change in this PR should work properly with it.
E.g.
- `z -` <kbd>Alt</kbd>+<kbd>=</kbd> should list the flags as completions.
- `z -` <kbd>Tab</kbd> should list the flags as completions (or if bound to `menu-complete` then it should cycle through inserting different flags, etc).

Add flags to the `z` arg matcher for Clink.

---

z.cmd

`z somedir` uses double `pushd` to tunnel the new path out past the
endlocal that restores the environment state.  But it ended up leaving
a pushd on the dir stack.
This change exploits normal variable expansion to restore the dir stack
to its initial state while still successfully tunneling the new path out
past the endlocal.

Fix leaked pushd

---

README.md

I don't know if the default of `builtin cd` is a good one, as opposed to a simple `cd`. It took me quite a bit of debugging before I figured out why, on my `fish` shell, changing directories with `z.lua` messed up the `cdh` (cd history) command. (On `fish`, `cd` is a function by default. It records the current directory in the history and then calls `builtin cd`).
I think the best thing would be to change the default. However, if you have a good reason to stick with it, I thought that documenting this potentially unexpected behavior might help.
Thank you, I really like using `z.lua`!

Add default to docs for $_ZL_CD

---

README.md

Most notably, this adds instructions of changing $_Z_CD.  I think many
`fish` users would find them useful. See #131 for more background.
This makes the installation instructions more conventional ([`|source`  instead of `psub`](https://fishshell.com/docs/current/fish_for_bash_users.html?highlight=psub#process-substitution)).
This also deletes the second (equivalent) set of instructions.
If the warning in that deleted sentence is important, we could add it back, but
it would apply to all the shells, wouldn't it? We could also de-emphasize it
by making it just a warning, something like
> You can instead manually insert the output of `lua /path/to/z.lua --init fish` 
> into the file, but then make sure to regenerate it every time you update or move `z.lua`.
Finally, some wording is …

Improve Fish installation instructions

---

z.lua

Corresponding "err" is "File exists". Resolves issues with paths marked invalid in case of network mapped drives (managed by ClearCase).

path valid if error code 17 by os.rename

---

README.md

`.zlua` file doesn't get created for Powershell users that use [Starship Prompt](https://starship.rs/) and place z.lua init command before starship init command in their `profile.ps1`.
Couldn't reproduce the bug in zsh. Didn't test other shells.

docs: added warning for powershell users

---

z.lua

fzf changed the option `--inline-info` to the equivalent `--info=inline` in release 0.19.0 with commit junegunn/fzf@d2fa4701651a1228ab7aea67eb195fc446f4a2a0 on 2019-11-14.

Update fzf --inline-info option to --info=inline

---

README.md
ranger_zlua.py

Makes Ranger plugin use the standard `$ZLUA_LUAEXE` and `$ZLUA_SCRIPT`
environment variables that `z.lua`, fixes error handling, adds docs.

Fixes and docs for the ranger plugin

---

z.lua

Substitute comma with dot before conversion

---

README.md
z.lua

If `z -b foo bar` finds no exact match in the path to the current directory,
it tries a "fuzzy" substitution with a frecent directory. For example, if
we are in `~/github/jekyll/test` and run `z -b jek gh`, it will try to
substitute the entire `jekyll` path component with `gh`. The result will
be equivalent to running `z ~/github gh test`.
The middle commit changes indentation, but is a no-op.
I've been using this for a bit. It seems nice.

Allow `z -b` to do fuzzy matching

---

z.lua

Hi, I'm the maintainer for [clink](https://github.com/chrisant996/clink).
I'd like to update z.lua with the following:
- Update the auto-init in z.lua to fix z.cmd, esp. the `HomeDir` environment variable so the Lua engine can find the z.lua script.
- Update the completions for z.lua in Clink, to include description strings and to add directory completions for the `-x` flag.

Clink changes

---

README.md
z.lua

Previously, you needed to set `_ZL_HYPHEN=1` to treat `-` as a normal
character.  Otherwise, it was treated as a Lua regexp special character, see
https://www.lua.org/pil/20.2.html. Note that it is not super-useful to treat
`-` as a special character; it is almost the same as `*` and the difference
is not very useful in the context of fuzzy matching.
Now, if `_ZL_HYPHEN` is not set, z.lua first tries to treat it as a regexp
character. If there are no results (which is likely if the user does not know
it's a special character), z.lua tries again, treating `-` as a normal
character this time.
If `_ZL_HYPHEN=0` or `_ZL_HYPHEN=1`, z.lua will always treat `-` as
either a regex symbol or as a normal character (respectively).
Hopefully, this will make the FAQ at …

Make z.lua try treating `-` as a normal character if there are no results

---

z.lua

Using '|' as the data separator caused crashes if
a path with a '|' char in it was in the data file. Changing that separator to a null byte ensures
that this kind of issue can never happen again as
the null byte can't be in a path.

Support '|' in path

---

README.cn.md
README.md
z.lua

Fix for #208 .
可能还需要一些进一步的测试和 review。

feat: add initial support for nushell (wip)

---

README.md

Fig is no more (see https://app.fig.io/plugins/z.lua)

Remove Fig

---

z.lua

The fzf interactive mode (`-I`) constructs a `tmpname` pathname and tries to sanitize it by stripping all `\` characters.  But it missed stripping all `:` characters, and the command printed this error output:
```
The filename, directory name, or volume label syntax is incorrect.
```
The `tmpname` looked like "c:\tmp\Temp\zlua_c:tmpTempsh2k0.txt", and the embedded `:` caused the error output.
This commit adds `:` to the list of characters to be stripped (only on Windows).

Fix invalid pathname in `z -I xyz` on Windows.

---

z.cmd
z.lua

This commit makes `z -i` and `z -I` go interactive even with no args.
Refer to skywind3000/z.lua#122 for context.

Make `z -i` and `z -I` with no arguments be interactive.

---

z.lua

When _ZL_MATCH_MODE=1 a script error occurs after `z -I` and <kbd>Ctrl</kbd>-<kbd>D</kbd>.
The code is missing a nil check.

Fix when _ZL_MATCH_MODE=1.
